### ISSUE TITLE
Storing/retrieving JSON data with errors

### ISSUE THREAD

**Issue by yingqiaogit** [glynnbird/bluemix_datacache#2]
In the case that the value is as a JSON object, the key/value pair can be stored successfully. However, during the retrieval on the key, the Parse Exception error occurs. 

In the case that the value is as a string (transformed by JSON.stringify()), the key/value pair can not be stored. 

Any suggestion?

**Comment by glynnbird** [comment]
The "get" method already JSON.parsed before it's returned e.g.

```
put("test",{a:1,b:"bob",c:true}, function(err,data) {
  console.log("POST",err,data);
  get("test", function(err, data) {
    console.log("GET",err,data);
    remove("test", function(err, data) {
      console.log("REMOVE",err,data);
    })
  })
});
```

**Comment by yingqiaogit** [comment]
I am not sure why it does not work in my case. I can see the data type is application/json in datacache. The error occurs from the get function when JSON.parse works on JSON data.  

I changed the get function as follows: 

var get = function(key, callback) {
  if (credentials == null) {
    return callback(true,null);
  }
  request(getOptions('GET', key), function(err, req, body) {
    try {
      //var retval = JSON.parse(body);
      var retval;

```
  if (typeof body == 'object')
       retval=body;
  else
       throw "error";

  callback(err, retval);
} catch(e) {
  console.log("Parse exception", body);
  callback(true, null);
}
```

  });
};

It works for the JSON data now. 

I may try your test tomorrow. 

Thanks a lot.

**Comment by yingqiaogit** [comment]
My testing shows that the Parse Exception occurs while retrieving a JSON data from the datacache. 

The testing code is as below:

datacache.put("test",{a:1,b:"bob",c:true}, function(err,data) {
    console.log("datacache test: POST",err,data);
    datacache.get("test", function(err, data) {
        console.log("datacache GET",err,data);
        datacache.remove("test", function(err, data) {
            console.log("datacache REMOVE",err,data);
        })
    })
});

The console log is as below: 

2015-08-07T13:48:05.63-0400 [App/0]      OUT datacache test: POST null <html>200</html>
2015-08-07T13:48:08.25-0400 [App/0]      OUT Parse exception { a: 1, b: 'bob', c: true }
2015-08-07T13:48:08.25-0400 [App/0]      OUT datacache GET null null
2015-08-07T13:48:08.95-0400 [App/0]      OUT datacache REMOVE null <html>200</html>
